services:
  postgres:
    image: postgres:17-alpine
    container_name: elois-store-postgres
    environment:
      POSTGRES_DB: elois_store
      POSTGRES_USER: elois
      POSTGRES_PASSWORD: elois_dev
    ports:
      - "5432:5432"
    volumes:
      - elois-store-postgres:/var/lib/postgresql/data

volumes:
  elois-store-postgres:
